name: wakelock_windows
description: >-2
  Windows platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.3.0
repository: https://github.com/jhonatan-3a/wakelock/tree/main/wakelock_windows

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  wakelock_platform_interface: ^0.3.0
  win32: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

# todo: use dartPluginClass declaration once that lands on stable (https://github.com/flutter/flutter/issues/52267_
#flutter:
#  plugin:
#    platforms:
#      windows:
#        dartPluginClass: WakelockWindows
